---
- hosts: servers
  vars:
    #Logwatch Email
    ubutnu_common_logwatch_email: replaceme@something.com
    
    #Pagakes to Install
    ubuntu_common_required_packages:
    - ufw
    - fail2ban
    - logwatch
    - unattended-upgrades

    #SSH Settings
    ubuntu_common_ssh_port: 22
    ubuntu_common_jss_port: 8443

  tasks:
    - name: Install required packages
      #loop through the vars above and install all packages
      apt: name={{ ubuntu_common_required_packages }} state=installed

    - name: Setup ufw
      ufw: state=enabled policy=deny
      ufw: rule=allow port={{ ubuntu_common_ssh_port }} proto=tcp
      ufw: rule=allow port={{ ubuntu_common_jss_port }} proto=tcp

      # Setup Logwatch to email daily summary
    - name: Email Logwatch Summay Daily
      lineinfile: 
        path: /etc/cron.daily/00logwatch
        regexp: '^/usr/sbin/logwatch'
        line: '/usr/sbin/logwatch --output mail --mailto {{ ubutnu_common_logwatch_email }} --detail high'
        state: present 
        create: yes

      # Setup unattended security updates/ copues apt_periodic file in directory
    - name: Setup unattended settings on apt
      copy: 
        src: apt_periodic
        dest: /etc/apt/apt.conf.d/10periodic

    - name: Setup unattended security and update channels on apt
      copy: 
        src: apt_periodic50
        dest: /etc/apt/apt.conf.d/50unattended-upgrades

      # SSH Welcome Message
      # Look for Banner line and uncomment it, use the /etc/issue.net banner
    - name: Change SSH Banner
      lineinfile:
        dest: /etc/ssh/sshd_config
        regexp: '^#Banner'
        line: 'Banner /etc/issue.net'
        backrefs: yes
      notify: Restart ssh

# @TODO backup exisiting issue.net file, rename issue.old and create new blank file
#    - name: Hide System Banner info
#      lineinfile:
#        dest: /etc/issue.net


  handlers:
    - name: Restart ssh
      service:
        name: ssh
        state: restarted
